parameters:
#    carnaval_user.example.class: Carnaval\UserBundle\Example

services:
#    carnaval_user.example:
#        class: %carnaval_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
