<?php

namespace Carnaval\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieVideoRepository extends EntityRepository
{
    public function getAllActiveCategorie()
    {
        // On récupère les résultats à partir de la Query
        return $this->getAllActiveCategorieQueryBuilder()
            ->getQuery()
            ->getResult();
    }

    public function getAllActiveCategorieQueryBuilder()
    {
        // La construction de la requête reste inchangée
        return $this->createQueryBuilder('a')
            ->where('a.isActive = :isact')
            ->setParameters(array(':isact'=> true));
    }
}
