<?php

namespace Carnaval\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends EntityRepository
{
    public function getAllEventsFromDate($date)
    {
        // La construction de la requête reste inchangée
        $query = $this->createQueryBuilder('a')
            ->where('a.isDeleted = :isdel')
            ->andWhere('a.eventDate >= :eventDate')
            ->setParameters(array(':isdel'=> false, ':eventDate'=> $date))
            ->orderBy('a.eventDate', 'ASC')
            ->getQuery();

        // On récupère les résultats à partir de la Query
        $resultats = $query->getResult();

        return $resultats;
    }
}
