<?php

namespace Carnaval\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LiensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiensRepository extends EntityRepository
{
}
