<?php

namespace Carnaval\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LiensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiensRepository extends EntityRepository
{
    public function getAllActiveLinks($categorie)
    {
        // La construction de la requête reste inchangée
        $query = $this->createQueryBuilder('a')
            ->where('a.isActive = :isact')
            ->andWhere('a.categorie >= :categorie')
            ->setParameters(array(':isact'=> true, ':categorie'=> $categorie))
            ->getQuery();

        // On récupère les résultats à partir de la Query
        $resultats = $query->getResult();

        return $resultats;
    }
}
