<?php

namespace Carnaval\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function getAllMessages()
    {
        // La construction de la requête reste inchangée
        $query = $this->createQueryBuilder('a')
            ->where('a.isDeleted = :isdel')
            ->andWhere('a.isArchived = :isarchived')
            ->setParameters(array(':isdel'=> false, ':isarchived'=> false))
            ->orderBy('a.receiveDate', 'ASC')
            ->getQuery();

        // On récupère les résultats à partir de la Query
        $resultats = $query->getResult();

        return $resultats;
    }
    public function getAllMessagesArchived()
    {
        // La construction de la requête reste inchangée
        $query = $this->createQueryBuilder('a')
            ->where('a.isDeleted = :isdel')
            ->andWhere('a.isArchived = :isarchived')
            ->setParameters(array(':isdel'=> false, ':isarchived'=> true))
            ->orderBy('a.receiveDate', 'ASC')
            ->getQuery();

        // On récupère les résultats à partir de la Query
        $resultats = $query->getResult();

        return $resultats;
    }
    public function getAllMessagesDeleted()
    {
        // La construction de la requête reste inchangée
        $query = $this->createQueryBuilder('a')
            ->where('a.isDeleted = :isdel')
            ->setParameters(array(':isdel'=> true))
            ->orderBy('a.receiveDate', 'ASC')
            ->getQuery();

        // On récupère les résultats à partir de la Query
        $resultats = $query->getResult();

        return $resultats;
    }
}
