<?php

namespace Carnaval\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends EntityRepository
{
    public function getActiveVideos()
    {
        // La construction de la requête reste inchangée
        $query = $this->createQueryBuilder('a')
            ->where('a.isActive = :isdel')
            ->setParameter(':isdel', false)
            ->getQuery();

        // On récupère les résultats à partir de la Query
        $resultats = $query->getResult();

        return $resultats;
    }

    public function getAllActiveVideos($categorie)
    {
        // La construction de la requête reste inchangée
        $query = $this->createQueryBuilder('a')
            ->where('a.isActive = :isact')
            ->andWhere('a.categorie = :categorie')
            ->setParameters(array(':isact'=> true, ':categorie'=> $categorie))
            ->getQuery();

        // On récupère les résultats à partir de la Query
        $resultats = $query->getResult();
        return $resultats;
    }
}
