carnaval_user:
    resource: "@CarnavalUserBundle/Resources/config/routing.yml"
    prefix:   /

carnaval_website:
    resource: "@CarnavalWebsiteBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: CarnavalUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout